apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-controller
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.17.3
    chart: sealed-secrets
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

